# Generated by Django 2.2.2 on 2019-12-31 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='books_types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_type_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('books_name', models.CharField(max_length=25)),
                ('author_name', models.CharField(max_length=25)),
                ('publisher_name', models.CharField(max_length=15)),
                ('books_numbers', models.IntegerField(default=1)),
                ('books_date', models.DateTimeField()),
                ('books_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lib_App.books_types')),
            ],
        ),
    ]
