# Generated by Django 2.2.2 on 2020-01-02 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lib_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='persons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.CharField(max_length=25)),
                ('person_type', models.CharField(choices=[('1', 'Professor'), ('2', 'Student'), ('3', 'Employ')], max_length=25)),
                ('person_name', models.CharField(max_length=25)),
                ('person_due', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateTimeField(blank=True, null=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lib_App.books')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lib_App.persons')),
            ],
        ),
    ]
