# Generated by Django 2.2.2 on 2020-01-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lib_App', '0003_auto_20200104_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persons',
            name='person_type',
            field=models.CharField(choices=[('Professor', 'Professor'), ('Student', 'Student'), ('Employ', 'Employ')], max_length=25),
        ),
    ]
