# Generated by Django 2.2.2 on 2020-01-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lib_App', '0004_auto_20200105_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='borrowerbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.CharField(max_length=25)),
                ('person_name', models.CharField(max_length=25)),
                ('book_name', models.CharField(max_length=25)),
                ('issue_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='returnbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.CharField(max_length=25)),
                ('person_name', models.CharField(max_length=25)),
                ('book_name', models.CharField(max_length=25)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Borrower',
        ),
    ]
