# Generated by Django 2.2.2 on 2020-01-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lib_App', '0005_auto_20200106_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowerbook',
            name='issue_date',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='returnbook',
            name='return_date',
            field=models.CharField(max_length=25),
        ),
    ]
